### ISSUE TITLE
Clarification on top level description of repo

### ISSUE THREAD

**Issue by chrisspruck** [PHPEmbark/PHPEmbark#20]
I noticed the repo description in my list of stars on here and by itself, I think "An introduction to PHP for beginners" sounds a bit misleading if you don't have the context, i.e. looking at the current README.

I suggest something more like "PHPEmbark is an open source, accessible curriculum package for instructors to use for teaching an introduction to PHP to beginners." There doesn't seem to be a size limit on the field when you make a new repo, so the above or similar should probably fit. Also, what about it makes it "accessible"? Is this to indicate "ease of use" or accessible in the "accessibility for the impaired" sense? Unless it's going to be ARIA/WCAG compliant, we might want to consider removing "accessible" or changing it to another term.

**Comment by ramsey** [comment]
Thanks, @chrisspruck! I agree with the suggestion you've made here. I'll make the updates and remove the word "accessible."

**Comment by ramsey** [comment]
Reopening this issue. I made the change to the README, and I thought I could update the repository description, but I don't have admin rights.

@auroraeosrose, will you update the repo description to read:

> PHPEmbark is an open-source curriculum package for instructors to use for teaching an introduction to PHP to beginners.

Thanks!

**Comment by chrisspruck** [comment]
Great, thanks!
