### ISSUE TITLE
Presentation for Section 2 (Internet and Forms)

### ISSUE THREAD

**Issue by auroraeosrose** [PHPEmbark/PHPEmbark#3]
Getting the presentation finished for section 2  and broken into lessions

**Comment by michellesanver** [comment]
What does "broken into lessons" entail exactly? It is hard for me to figure out what I should actually do which makes it hard for me to progress. I don't know the format of this, I know there's supposed to be "some presentation and some exercises" but what does exercises entail in "Internet and forms"? Can we maybe discuss this a bit further?

**Comment by auroraeosrose** [comment]
I was thinking something along the lines of 

"this is HTTP and it uses sockets - here are some basics about it" 
with exercises being some use of perhaps "get_header" and "getallheaders" (yes this works in cli server in 5.6)

"this is the basics of a request and response in PHP" and a discussion of lack of state
some exercise involving sessions would be good here

"This is how to create an html form and this is what PHP shows" with a basic discussion of http and sending information

Then expand a bit into http verbs, get, and post with additional exercises relating

Possibly end with something "fancy" like using header for 302 redirects 

exercises being either a question to be "answered" with a small piece of coding,
or a small piece of unfinished code to be completed
or a piece of code to be run and possibly altered to do something

**Comment by auroraeosrose** [comment]
Round 1 of this is done - thanks @e3betht
